name: C/C++ build and test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:

jobs:
# Build the C++ library & test that it is working using GoogleTest
  build-and-test-cpp:
    name: C/C++ Library on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - name: Build and test (Linux & macOS)
        run: cmake --workflow --preset build-and-test-release