name: documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
# Build the C++ library & test that it is working using GoogleTest
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get install doxygen
      - name: Build documentation in sphinx/docs
        run: |
          cmake --workflow --preset build-docs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/docs/html/'
      - name: Deploy to GitHub Pages
        id: build-documentation
        uses: actions/deploy-pages@v4